FROM caddy:2.9.1-builder AS builder

# https://caddyserver.com/docs/modules/http.handlers.replace_response
RUN xcaddy build --with github.com/caddyserver/replace-response

FROM caddy:2.9.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy